### ISSUE TITLE
Differences in annotate_SJ.R diposited in Baltica and scripts folder

### ISSUE THREAD

**Issue by Antgomoplx** [dieterich-lab/Baltica#19]
Hi,

I saw differences in Baltica's actual release regarding this script ( the one in Baltica's folder) compared to the one located in scripts folder. In the first one I see that the function filter_hits_by_diff is not used, so as far this is the main point of the results integration among all 4 methods (https://dieterich-lab.github.io/Baltica/integration.html#annotating-the-results) I want to know if this has changed by the use of the simple merge by coordinates in the script ( line 354)

Many thanks in advance!

**Comment by tbrittoborges** [comment]
Hi, [Antgomoplx](https://github.com/Antgomoplx), you are correct. Currently, `filter_hits_by_diff` is not used as we recently preferred to keep the integration simple. I will correct the error in the documentation. Thank you for the feedback! 

Just to detail:
- `filter_hits_by_diff` method allows any SJ with a maximum n nt (defaults to 2) difference to "cluster" - we assume these are the same. 
- the current approach uses `integrate_coordinates` to find the most common difference in nt between the query and the reference annotation and uses this number to offset the coordinates. 

(sorry about the delay, I am out of the office)

**Comment by tbrittoborges** [comment]
fixed in bad2483
