### ISSUE TITLE
How to change location where singularity containers are stored ...

### ISSUE THREAD

**Issue by aghr** [dieterich-lab/Baltica#20]
... from the standard location $HOME/.baltica/singularity/ to another user-specified location? 

Many thanks
Andre

**Comment by tbrittoborges** [comment]
Hi Andre,

You can use `--singularity-prefix prefix_to_location`, for example, assuming you want to save the singularity containers at the working directory:

```{bash}
baltica rmats config.yml --use-singularity --profile slurm --singularity-prefix $PWD/.singularity
```
This command will run rmats for the project in `config.yml`. In that case, Singularity will save the containers at `$PWD/.singularity`.
If you need to rerun rmats, using the same prefix will not require downloading the container. 

I will update the documentation to make this feature clear. I appreciate your interest and let me know if you have further questions.
Thiago
