### ISSUE TITLE
LeafCutter Error

### ISSUE THREAD

**Issue by AlessandraLongo** [dieterich-lab/Baltica#25]
Hello everyone,
I'm encountering an issue while running a Baltica workflow (version 1.2.4, python 3.7.12) with unstranded RNA-seq data. The execution halted at LeafCutter differential splicing analysis step. Here’s a summary of the error message: 

Command: baltica all path/to/config.yaml - - use-singularity - -verbose - -cores 10
>>Executing subworkflow leafcutter.
Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 18
Rules claiming more threads will be scaled down.
Job stats:
job                                 count
--------------------------------  -------
leafcutter_differential_splicing        1
total                                   1

Select jobs to execute...

[Thu Oct 31 15:34:34 2024]
rule leafcutter_differential_splicing:
    input: leafcutter/exons.gtf.gz, leafcutter/RGNEF-vs-CTR/RGNEF-vs-CTR_perind_numers.counts.gz, leafcutter/RGNEF-vs-CTR/diff_introns.txt
    output: leafcutter/RGNEF-vs-CTR/RGNEF-vs-CTR_cluster_significance.txt
    log: logs/leafcutter/leafcutter_differential_splicing/RGNEF-vs-CTR.log
    jobid: 0
    reason: Missing output files: leafcutter/RGNEF-vs-CTR/RGNEF-vs-CTR_cluster_significance.txt
    wildcards: comp_names=RGNEF-vs-CTR
    threads: 10
    resources: tmpdir=/tmp

Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 18
Rules claiming more threads will be scaled down.
Select jobs to execute...
Activating singularity image /home/cappelli/.baltica/singularity/2f0497e2227c782b99d020de15ba0db2.simg
/bin/bash: /root/.bashrc: Permission denied
Loading counts from leafcutter/RGNEF-vs-CTR/RGNEF-vs-CTR_perind_numers.counts.gz 
Loading metadata from leafcutter/RGNEF-vs-CTR/diff_introns.txt 
Encoding as CTR =0, RGNEF =1
Settings:
$output_prefix
[1] "leafcutter/RGNEF-vs-CTR/RGNEF-vs-CTR"
$max_cluster_size
[1] Inf
$min_samples_per_intron
[1] 2
$min_samples_per_group
[1] 2
$min_coverage
[1] 5
$timeout
[1] 30
$num_threads
[1] 10
$exon_file
[1] "leafcutter/exons.gtf.gz"
$init
[1] "smart"
$seed
[1] 12345
$help
[1] FALSE

Running differential splicing analysis...
[Thu Oct 31 15:34:36 2024]
Error in rule leafcutter_differential_splicing:
    jobid: 0
    input: leafcutter/exons.gtf.gz, leafcutter/RGNEF-vs-CTR/RGNEF-vs-CTR_perind_numers.counts.gz, leafcutter/RGNEF-vs-CTR/diff_introns.txt
    output: leafcutter/RGNEF-vs-CTR/RGNEF-vs-CTR_cluster_significance.txt
    log: logs/leafcutter/leafcutter_differential_splicing/RGNEF-vs-CTR.log (check log file(s) for error details)
    shell:
        
        leafcutter_ds_pair.R --exon_file=leafcutter/exons.gtf.gz         --min_coverage 5          leafcutter/RGNEF-vs-CTR/RGNEF-vs-CTR_perind_numers.counts.gz leafcutter/RGNEF-vs-CTR/diff_introns.txt --num_threads 10 --output_prefix=leafcutter/RGNEF-vs-CTR/RGNEF-vs-CTR         -i 2 -g 2 2> logs/leafcutter/leafcutter_differential_splicing/RGNEF-vs-CTR.log
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2024-10-31T153434.446038.snakemake.log<<

From the RGNEF-vs-CTR.log I got this: 
Loading required package: Rcpp
Loading required package: doMC
Loading required package: foreach
Loading required package: iterators
Loading required package: parallel
Error in `colnames<-`(`*tmp*`, value = c("chr", "start", "end", "clu")) : 
  attempt to set 'colnames' on an object with less than two dimensions
Calls: differential_splicing -> get_intron_meta -> colnames<-
Execution halted

Plus, also the intron_clustering.log reported a strange output:
scanning /home/cappelli/Desktop/Baltica_RGNEF/leafcutter/CTR_1.junc...
scanning /home/cappelli/Desktop/Baltica_RGNEF/leafcutter/CTR_2.junc...
scanning /home/cappelli/Desktop/Baltica_RGNEF/leafcutter/CTR_3.junc...
scanning /home/cappelli/Desktop/Baltica_RGNEF/leafcutter/RGNEF_1.junc...
scanning /home/cappelli/Desktop/Baltica_RGNEF/leafcutter/RGNEF_2.junc...
scanning /home/cappelli/Desktop/Baltica_RGNEF/leafcutter/RGNEF_3.junc...
Parsing...

Wrote 0 clusters..
Split into 0 clusters...
Sorting /home/cappelli/Desktop/Baltica_RGNEF/leafcutter/CTR_1.junc..
Sorting /home/cappelli/Desktop/Baltica_RGNEF/leafcutter/CTR_2.junc..
Sorting /home/cappelli/Desktop/Baltica_RGNEF/leafcutter/CTR_3.junc..
Sorting /home/cappelli/Desktop/Baltica_RGNEF/leafcutter/RGNEF_1.junc..
Sorting /home/cappelli/Desktop/Baltica_RGNEF/leafcutter/RGNEF_2.junc..
Sorting /home/cappelli/Desktop/Baltica_RGNEF/leafcutter/RGNEF_3.junc..
merging 6 junction files...
merging 6 files done.

I am not sure if it is an upstream input file problem (I used an annotation.gtf file converted from gff3 using Agat) cause I checked the format and seems to be correct.

Any insights or suggestions would be greatly appreciated!
Thank you for your help!

Alessandra

**Comment by tbrittoborges** [comment]
The origin of the problem here is on this line: `Wrote 0 clusters..` This means no clusters (splicing events) were selected. Which GTF/GFF annotation are you using? Is it the same you used to align the BAM files?

**Comment by AlessandraLongo** [comment]
Sorry for the late reply, I actually repeated the analysis. The first time I used a different annotation file, now instead I used the one used for the alignment and got the same error.

**Comment by tbrittoborges** [comment]
Can you please subset one bam file and the gtf to chromosome 10 and then upload it here so I can check this leafcutter issue?

**Comment by AlessandraLongo** [comment]
Here they are, I also checked the .junc files and seemed to be ok, I just noticed that there is “?” in the strand column, is this a problem?

Thank you very much for your help

Alessandra

Da: Thiago Britto Borges ***@***.***>
Data: giovedì, 28 novembre 2024 alle ore 12:42
A: dieterich-lab/Baltica ***@***.***>
Cc: AlessandraLongo ***@***.***>, Author ***@***.***>
Oggetto: Re: [dieterich-lab/Baltica] LeafCutter Error (Issue #25)

Can you please subset one bam file and the gtf to chromosome 10 and then upload it here so I can check this leafcutter issue?

**Comment by tbrittoborges** [comment]
Please upload the files on GitHub, sending it by email does not attach it here.

**Comment by AlessandraLongo** [comment]
Sorry 
The files exceed the allowed limit, so I have created a repository: https://github.com/AlessandraLongo/Baltica_Issue-25.git

**Comment by AlessandraLongo** [comment]
Hi, sorry to bother you again 
I hope that the files were correctly shared and kindly ask if there are any insights about the error I'm experiencing.
Thank you very much for your time and support

**Comment by tbrittoborges** [comment]
The bam file is missing the headers, so I cannot work with it. 
The error you report could be due to a mismatch between the bam file and gtf you are using.

Let's try a different approach, do you have `samtools` available? We can check the GAPDH coordinates for checking for reads. Can you run the following command, replace control1.bam for your bam file (not the subset one) :

```bash
samtools view control1.bam  "12:6534517-6538371" | less
```

Do you see this message? 
`[main_samview] region "12:6534517-6538371" specifies an invalid region or unknown reference. Continue anyway.`

Alternatlively:

```bash
samtools view control1.bam  "chr12:6534517-6538371" | less
```
Can you see reads?

**Comment by AlessandraLongo** [comment]
I've checked  both commands and got that message with the first one, while I see the reads with the second.

**Comment by tbrittoborges** [comment]
Great, so they match. I will try to reproduce this error and will get back to you tomorrow.

Another question, are these files paired-end? What library strategy are you using ([here](https://chipster.csc.fi/manual/library-type-summary.html) for the two types)?

**Comment by AlessandraLongo** [comment]
Yes, they are all paired-end and unstranded.
Again, thank very much for your time

**Comment by tbrittoborges** [comment]
I apologize for the delaying getting back to you. Baltica works gencode or ensembl, which uses different chr notations. But I found a related issue: https://github.com/davidaknowles/leafcutter/issues/52#issuecomment-431975589
This issue suggests you may have non-canonical seqnames (chromosomes) on your data. Does that make any sense?

**Comment by AlessandraLongo** [comment]
Hi, I checked the chr indication from bam with samtools view -h and they all look like this: 
@SQ	SN:chr1	LN:249250621
@SQ	SN:chr2	LN:243199373
@SQ	SN:chr3	LN:198022430
@SQ	SN:chr4	LN:191154276
@SQ	SN:chr5	LN:180915260
@SQ	SN:chr6	LN:171115067
@SQ	SN:chr7	LN:159138663
@SQ	SN:chr8	LN:146364022
@SQ	SN:chr9	LN:141213431
@SQ	SN:chr10	LN:135534747
@SQ	SN:chr11	LN:135006516
@SQ	SN:chr12	LN:133851895
@SQ	SN:chr13	LN:115169878
@SQ	SN:chr14	LN:107349540
@SQ	SN:chr15	LN:102531392
@SQ	SN:chr16	LN:90354753
@SQ	SN:chr17	LN:81195210
@SQ	SN:chr18	LN:78077248
@SQ	SN:chr19	LN:59128983
@SQ	SN:chr20	LN:63025520
@SQ	SN:chr21	LN:48129895
@SQ	SN:chr22	LN:51304566
@SQ	SN:chrX	LN:155270560
@SQ	SN:chrY	LN:59373566
@SQ	SN:chrMT	LN:16569

Should I add the --checkchrom option?

**Comment by tbrittoborges** [comment]
I don't see any non-canonical seqnames here. Can you try running this clustering step with --checkchrom TRUE?

You should be able to run leafcutter from the singularity container that Baltica uses ( /home/cappelli/.baltica/singularity/2f0497e2227c782b99d020de15ba0db2.simg).

**Comment by AlessandraLongo** [comment]
I run and got this error 
Singularity> python /opt/conda/bin/leafcutter_cluster_regtools_py3.py \
>     -j /home/cappelli/Desktop/Baltica_New_RGNEF/output/leafcutter/CTR_1.junc \
>     -o /home/cappelli/Desktop/Leafcutter_RG \
>     --checkchrom TRUE
chr1	11555	12104	JUNC00000001	2	?	11555	12104	255,0,02116,95	0,454 does not exist... check your junction files. What could be the problem here?

**Comment by tbrittoborges** [comment]
From the container, can you try:
```
file /home/cappelli/Desktop/Baltica_New_RGNEF/output/leafcutter/CTR_1.junc 
```

To check if the file is accessible?

**Comment by tbrittoborges** [comment]
And can also post the first few lines of `CTR_1.junc`?

Are you allowed to share the bam and gtf files that you, are you using? If so, please upload them here: https://cloud.crc1550.com/index.php/s/GN7atmoBgXiLoiL

- 1 bam file
- the GTF file that you used for bam alignment

**Comment by AlessandraLongo** [comment]
permission is fine: -rw-rw-r--
head junction file: 
head /home/cappelli/Desktop/Baltica_New_RGNEF/output/leafcutter/CTR_1.junc
chr1	11555	12104	JUNC00000001	2	?	11555	12104	255,0,02116,95	0,454
chr1	14688	15088	JUNC00000002	600	?	14688	15088	255,0,02141,119	0,281
chr1	14705	15040	JUNC00000003	3	?	14705	15040	255,0,02109,71	0,264
chr1	14713	15039	JUNC00000004	6	?	14713	15039	255,0,02116,110	0,216
chr1	14765	15038	JUNC00000006	4	?	14765	15038	255,0,0264,18	0,255
chr1	14956	15931	JUNC00000005	143	?	14956	15931	255,0,0282,136	0,839
chr1	15813	16746	JUNC00000007	68	?	15813	16746	255,0,02134,140	0,793
chr1	15923	16736	JUNC00000008	8	?	15923	16736	255,0,02104,130	0,683
chr1	16212	16728	JUNC00000009	7	?	16212	16728	255,0,0298,122	0,394
chr1	16628	16997	JUNC00000010	455	?	16628	16997	255,0,02137,140	0,229
I've uploaded both files on the cloud 
I forgot to specify that I performed Star alignment on trimmed reads (using Trimmomatic), is this ok for Baltica?

**Comment by tbrittoborges** [comment]
Yes, trimming is fine, we also trim our reads.

I will try to reproduce the problem and get back to you.

**Comment by tbrittoborges** [comment]
So the problem here is that all the junctions are reporting unstranded (the `?` that you reported). I don't remember seem anything like this, what read aligner are you using? 
Splice-aware aligners, such as STAR, use the intron motifs to identify for the read genomic strand, and this is added to the XS tag. You may need to realign with STAR or check for a similar option on your favorite program.

**Comment by tbrittoborges** [comment]
I noticed that you used STAR. I guess you have too options now:
- Re aligned with the `--outSAMstrandField intronMotif` option. 
- Using the tagXSstrandedData.awk Script (I have no experience with this): https://github.com/alexdobin/STAR/issues/2008

**Comment by AlessandraLongo** [comment]
Got it! I'll realigned with that Star option, hope it works 
Thank you sooo much for your help and time :)

**Comment by tbrittoborges** [comment]
Fell free to reopen if the problem persists.
